Repository Precipice-Games/Odyseed, pull requests merged in 2023-02, with the labels that each got.

#40 Sound Effects
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_1.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_1.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_2.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_2.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_3.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_3.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_4.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_4.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_5.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_5.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_6.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_6.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_7.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_7.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_8.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_8.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_9.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Bounce_9.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_Coin.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Coin.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_Crate.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Crate.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_Hurt.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Hurt.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_LevelMusic_1.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_LevelMusic_1.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_LevelMusic_2.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_LevelMusic_2.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_LevelMusic_3.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_LevelMusic_3.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_Pot_1.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Pot_1.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_Pot_2.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Pot_2.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_Pot_3.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Pot_3.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_Tendril_Detach.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Tendril_Detach.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_Tendril_Grow.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Tendril_Grow.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_UI_Click.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_UI_Click.mp3.meta
  UntitledRootsGame/Assets/Roots/Audio/S_Water.mp3
  UntitledRootsGame/Assets/Roots/Audio/S_Water.mp3.meta
  UntitledRootsGame/Assets/Roots/MaterialLibrary/FX/Stars/FX_Stars.prefab
  UntitledRootsGame/Assets/Roots/UI/Title.png
  UntitledRootsGame/Assets/Roots/UI/Title.png.meta
  UntitledRootsGame/Assets/Roots/_Scenes/Menu.unity
Labels: enhancement

#62 Improved wind mechanics and configurability
  UntitledRootsGame/Assets/Developers/Johnson/Wind.cs
  UntitledRootsGame/Assets/Developers/Johnson/WindBlown.cs
  UntitledRootsGame/Assets/Developers/Johnson/WindLibrary/P_Wind_Gusty.prefab
  UntitledRootsGame/Assets/Developers/Johnson/WindLibrary/P_Wind_Gusty.prefab.meta
  UntitledRootsGame/Assets/Developers/Johnson/WindLibrary/P_Wind_Steady.prefab
  UntitledRootsGame/Assets/Developers/Johnson/WindLibrary/P_Wind_Steady.prefab.meta
  UntitledRootsGame/Assets/Developers/Johnson/WindLibrary/P_Wind_Turbulent.prefab
  UntitledRootsGame/Assets/Developers/Johnson/WindLibrary/P_Wind_Vortex.prefab
  UntitledRootsGame/Assets/Developers/Johnson/WindLibrary/P_Wind_Wave.prefab
Labels: enhancement

#64 Fixed wind bug.
  UntitledRootsGame/Assets/Developers/Johnson/Wind.cs
  UntitledRootsGame/Assets/Developers/Johnson/WindLibrary/P_Wind_Gusty.prefab
  UntitledRootsGame/Assets/Developers/Johnson/WindLibrary/P_Wind_Steady.prefab
  UntitledRootsGame/Assets/Developers/Johnson/WindLibrary/P_Wind_Turbulent.prefab
  UntitledRootsGame/Assets/Developers/Johnson/WindLibrary/P_Wind_Vortex.prefab
  UntitledRootsGame/Assets/Developers/Johnson/WindLibrary/P_Wind_Wave.prefab
  UntitledRootsGame/Assets/Roots/Environment/Skybox/FS000_Day_01.mat
  UntitledRootsGame/Assets/Roots/_Scenes/Level_01.unity
  UntitledRootsGame/Assets/Roots/_Scenes/Level_02.unity
  UntitledRootsGame/Assets/Roots/_Scenes/Level_03.unity
Labels: bug

#66 Thorns fix.
  UntitledRootsGame/Assets/Roots/Environment/P_TileBlock_Thorns.prefab
Labels: bug

#71 69 visual and physics improvements for pappus
  UntitledRootsGame/Assets/Developers/Johnson/BrootusController.cs
  UntitledRootsGame/Assets/Developers/Johnson/Level_01.unity
  UntitledRootsGame/Assets/Developers/Johnson/Level_01.unity.meta
  UntitledRootsGame/Assets/Developers/Johnson/RootSystem.cs
  UntitledRootsGame/Assets/Developers/Johnson/Sandbox.unity
  UntitledRootsGame/Assets/Developers/Johnson/Wind.cs
  UntitledRootsGame/Assets/Developers/Johnson/WindBlown.cs
  UntitledRootsGame/Assets/Roots/Characters/P_Character_Tendrils_Connected.prefab
  UntitledRootsGame/Assets/Roots/Characters/P_Player.prefab
  UntitledRootsGame/Assets/Roots/Characters/Pappus.prefab
  UntitledRootsGame/Assets/Roots/Characters/Pappus.prefab.meta
  UntitledRootsGame/Assets/Roots/_Scenes/Level_01.unity
Labels: bug, enhancement

#79 Initial doxyfile and GitHub workflow action.
  .github/workflows/update-docs.yaml
  Doxyfile
Labels: documentation

#80 Updated overview and added external links to readme.
  README.md
Labels: documentation

#81 Fixed accidental absolute path
  Doxyfile
Labels: bug

#83 A few fixes for an improved GitHub pages experience, resolves #82.
  .github/workflows/update-docs.yaml
  Doxyfile
  docs/index.md
Labels: documentation

#84 Reverting previous changes because they failed
  .github/workflows/update-docs.yaml
  Doxyfile
  docs/index.md
Labels: bug, documentation
